apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: your-namespace
spec:
  selector:
    app: nginx # Change 'my-app' to 'nginx'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
